#
# This file controls the details on the published HTML page.
#
# All the values here are optional, but it will obviously look a lot
# better if you fill them in.
#
# Remove the # from the front of each line, and then edit appropriately.
#

title: Seasonality in dominant upper-ocean dynamics at submesoscales
abstract: To be completed.

# This controls which file is shown on the right-hand side of the published
# HTML page.  By default it will take the first PDF or HTML file that it
# finds.  If that doesn't work for you, you can specify the correct file here.
#iframe_src: book.pdf

# You can specify multiple authors, just follow the pattern below.
# These fields can contain HTML tags.  You probably want to put <br />
# in the address somewhere, indicating a line break.

authors:
- name: Cesar B. Rocha
  address: Scripps Institution of Oceanography, 9500 Gilman Dr. 0213, La Jolla, CA 92093-0213, USA.

#- name: Clara McNarma
#  address: School of Dance and Drama,<br />College of the Northern Light,<br />Dogger, Fisher, German Bight.
github_username: crocha700
github_repo: UpperOceanSeasonality
iframe_src: rocha_etal.pdf
